check my commit Petranovski_HW3_Human
javaGuruBY/java-free-stream-5 pull request #97
Opened 2020-07-24 08:17 UTC by VladimirPetranovski

2020-07-24 08:25 UTC, bzsh submitted a review, later dismissed
lgfm

2020-07-24 12:16 UTC, barilo-egor requested changes

2020-07-24 12:16 UTC, barilo-egor commented on homeWork_03/ex2_Human/petranovski/petranovski/service/HumanService.java
> +    Human human = new Human("Bob Marley", 40);
Создание объектов не должно происходить в бизнес-логике, конкретно здесь это ты должен делать в psvm.Исправь метод greet: добавь принимаемое значение типа Human, и уже от получаемого Human'a будет браться имя и возраст.
После этого ты сможешь создать кучу человеков и каждого из них отправлять в метод greet, после чего каждый из них будет здороваться.
А сейчас у тебя будет здороваться только Боб.

2020-07-25 07:30 UTC, VladimirPetranovski commented on homeWork_03/ex2_Human/petranovski/petranovski/service/HumanService.java
> +    Human human = new Human("Bob Marley", 40);
made changes to the HumanService and HumanDemo classes

2020-07-25 09:04 UTC, VladimirPetranovski commented
> lgfm

Привет, ты не поставил мне апрув), поставь плиз!

2020-07-25 09:20 UTC, AnastasiaKichaeva approved these changes

2020-07-25 11:07 UTC, barilo-egor approved these changes
lgfm

2020-07-26 10:33 UTC, TLittleProgrammer approved these changes
lgfm

2020-07-26 17:17 UTC, AnastasiaKichaeva approved these changes

2020-07-27 07:46 UTC, rus-sto approved these changes
lgfm

2020-07-27 13:12 UTC, merged